// <auto-generated />
namespace CinemaApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202103271940178_user_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
